config/routes.rb
Rails.application.routes.draw do

  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  post 'items' => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <div class="form">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>

  

app/views/items/index.html.erb
<h1>Hello</h1>

<ul>
	<% @items.each do |item| %>
		<li><%=item.name%> <%=item.price%></li>
	<% end %>
</ul>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<br>
<div class="button">
<%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>